gets list of all articles
andmikpar/fe-nc-news pull request #1
Opened 2023-01-09 16:08 UTC by andmikpar

2023-01-09 16:15 UTC, popatre requested changes
Could you add some loading state to let us know something is happening?

2023-01-09 16:15 UTC, popatre commented on src/components/Articles.jsx
> +    });
Need to handle the loading here as well

2023-01-10 09:43 UTC, B7Bprog approved these changes
Great work Andy, responsive design, great visual feedback of loading pages, good use of utils functions for API requests. Please consider my other comment, then merge. 🎉

2023-01-10 09:43 UTC, B7Bprog commented on src/components/Articles.jsx
> +          <div className="article">
You could add a 'key' attribute to this tag with the article_id for example to let react to track it. It still works without doing so though.

2023-01-10 10:33 UTC, merged